services:
  - type: web
    name: certicart-web
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    postDeployCommand: |
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
      php artisan db:seed --force
      php artisan storage:link
    envVars:
      - key: APP_NAME
        value: CertiCarte
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: FILESYSTEM_DISK
        value: public
      - key: VIEW_COMPILED_PATH
        value: /var/www/html/storage/framework/views
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: "120"
      - key: CACHE_STORE
        value: database
      - key: CACHE_PREFIX
        value: certicart_cache
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: certicart-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: certicart-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: certicart-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: certicart-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: certicart-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: certicart-db
          property: connectionString
      - key: DB_SCHEMA
        value: public
      - key: MAIL_MAILER
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        sync: false

databases:
  - name: certicart-db
    plan: free
    region: oregon
