services:
  - type: web
    name: certicarte
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          name: certicarte
          type: web
          property: host
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: certicarte-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: certicarte-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: certicarte-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: certicarte-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: certicarte-db
          property: password

databases:
  - name: certicarte-db
    databaseName: certicarte
    user: certicarte_user
    plan: free

